export type VoiceEmotion = { label: string; value: string };
export type VoiceCatalogItem = {
  id: string;
  name: string;
  description?: string;
  emotions?: VoiceEmotion[];
};

const 情感通用: VoiceEmotion[] = [
  { label: "开心", value: "happy" },
  { label: "悲伤", value: "sad" },
  { label: "愤怒", value: "angry" },
  { label: "害怕", value: "scare" },
  { label: "厌恶", value: "hate" },
  { label: "惊讶", value: "surprise" },
  { label: "哭腔", value: "tear" },
];

export const BUILTIN_MANDARIN_VOICES: VoiceCatalogItem[] = [
  { id: "BV700_V2_streaming", name: "灿灿 2.0", description: "多情感/风格", emotions: [...情感通用, { label: "愉悦", value: "pleased" }, { label: "抱歉", value: "sorry" }, { label: "嗔怪", value: "annoyed" }, { label: "客服", value: "customer_service" }, { label: "专业", value: "professional" }, { label: "严肃", value: "serious" }, { label: "傲娇", value: "tsundere" }, { label: "安慰鼓励", value: "comfort" }, { label: "绿茶", value: "conniving" }, { label: "娇媚", value: "charming" }, { label: "情感电台", value: "radio" }, { label: "撒娇", value: "lovey-dovey" }, { label: "瑜伽", value: "yoga" }, { label: "讲故事", value: "storytelling" }] },
  { id: "BV705_streaming", name: "炀炀", description: "多情感/风格", emotions: [{ label: "愉悦", value: "pleased" }, { label: "抱歉", value: "sorry" }, { label: "嗔怪", value: "annoyed" }, { label: "安慰鼓励", value: "comfort" }, { label: "讲故事", value: "storytelling" }, { label: "自然对话", value: "chat" }] },
  { id: "BV701_V2_streaming", name: "擎苍 2.0", description: "多情感", emotions: [...情感通用, { label: "旁白-舒缓", value: "narrator" }, { label: "旁白-沉浸", value: "narrator_immersive" }, { label: "平和", value: "novel_dialog" }] },
  { id: "BV001_V2_streaming", name: "通用女声 2.0", description: "普通话" },
  { id: "BV700_streaming", name: "灿灿", description: "多情感/风格", emotions: [...情感通用, { label: "愉悦", value: "pleased" }, { label: "抱歉", value: "sorry" }, { label: "嗔怪", value: "annoyed" }] },
  { id: "BV406_V2_streaming", name: "超自然音色-梓梓2.0", description: "普通话" },
  { id: "BV406_streaming", name: "超自然音色-梓梓", description: "多情感", emotions: [...情感通用] },
  { id: "BV407_V2_streaming", name: "超自然音色-燃燃2.0", description: "普通话" },
  { id: "BV407_streaming", name: "超自然音色-燃燃", description: "普通话" },
  { id: "BV001_streaming", name: "通用女声", description: "多情感", emotions: [...情感通用, { label: "助手", value: "assistant" }, { label: "客服", value: "customer_service" }, { label: "安慰鼓励", value: "comfort" }, { label: "广告", value: "advertising" }, { label: "讲故事", value: "storytelling" }] },
  { id: "BV002_streaming", name: "通用男声", description: "普通话" },
  { id: "BV701_streaming", name: "擎苍", description: "多情感", emotions: [...情感通用, { label: "旁白-舒缓", value: "narrator" }, { label: "旁白-沉浸", value: "narrator_immersive" }, { label: "平和", value: "novel_dialog" }] },
  { id: "BV123_streaming", name: "阳光青年", description: "有声阅读" },
  { id: "BV120_streaming", name: "反卷青年", description: "有声阅读/视频配音" },
  { id: "BV119_streaming", name: "通用赘婿", description: "有声阅读" },
  { id: "BV115_streaming", name: "古风少御", description: "有声阅读" },
  { id: "BV107_streaming", name: "霸气青叔", description: "有声阅读" },
  { id: "BV100_streaming", name: "质朴青年", description: "有声阅读" },
  { id: "BV104_streaming", name: "温柔淑女", description: "有声阅读" },
  { id: "BV004_streaming", name: "开朗青年", description: "有声阅读" },
  { id: "BV113_streaming", name: "甜宠少御", description: "有声阅读" },
  { id: "BV102_streaming", name: "儒雅青年", description: "有声阅读" },
  { id: "BV405_streaming", name: "甜美小源", description: "智能助手" },
  { id: "BV007_streaming", name: "亲切女声", description: "智能助手" },
  { id: "BV009_streaming", name: "知性女声", description: "智能助手" },
  { id: "BV419_streaming", name: "诚诚", description: "智能助手" },
  { id: "BV415_streaming", name: "童童", description: "智能助手" },
  { id: "BV008_streaming", name: "亲切男声", description: "智能助手" },
  { id: "BV408_streaming", name: "译制片男声", description: "视频配音" },
  { id: "BV426_streaming", name: "懒小羊", description: "视频配音" },
  { id: "BV428_streaming", name: "清新文艺女声", description: "视频配音" },
  { id: "BV403_streaming", name: "鸡汤女声", description: "视频配音" },
  { id: "BV158_streaming", name: "智慧老者", description: "视频配音" },
  { id: "BV157_streaming", name: "慈爱姥姥", description: "视频配音" },
  { id: "BR001_streaming", name: "说唱小哥", description: "视频配音" },
  { id: "BV410_streaming", name: "活力解说男", description: "视频配音" },
  { id: "BV411_streaming", name: "影视解说小帅", description: "视频配音" },
  { id: "BV437_streaming", name: "解说小帅-多情感", description: "多情感", emotions: [...情感通用] },
  { id: "BV412_streaming", name: "影视解说小美", description: "视频配音" },
  { id: "BV159_streaming", name: "纨绔青年", description: "视频配音" },
  { id: "BV418_streaming", name: "直播一姐", description: "视频配音" },
  { id: "BV142_streaming", name: "沉稳解说男", description: "视频配音" },
  { id: "BV143_streaming", name: "潇洒青年", description: "视频配音" },
  { id: "BV056_streaming", name: "阳光男声", description: "视频配音" },
  { id: "BV005_streaming", name: "活泼女声", description: "视频配音" },
  { id: "BV064_streaming", name: "小萝莉", description: "多情感", emotions: [...情感通用] },
  { id: "BV051_streaming", name: "奶气萌娃", description: "特色音色" },
  { id: "BV063_streaming", name: "动漫海绵", description: "特色音色" },
  { id: "BV417_streaming", name: "动漫海星", description: "特色音色" },
  { id: "BV050_streaming", name: "动漫小新", description: "特色音色" },
  { id: "BV061_streaming", name: "天才童声", description: "特色音色" },
  { id: "BV401_streaming", name: "促销男声", description: "广告配音" },
  { id: "BV402_streaming", name: "促销女声", description: "广告配音" },
  { id: "BV006_streaming", name: "磁性男声", description: "广告配音" },
  { id: "BV011_streaming", name: "新闻女声", description: "新闻播报" },
  { id: "BV012_streaming", name: "新闻男声", description: "新闻播报" },
  { id: "BV034_streaming", name: "知性姐姐-双语", description: "教育场景" },
  { id: "BV033_streaming", name: "温柔小哥", description: "教育场景" },
];

